#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Tazlin <tazlin.on.github@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Generates the throwaway Garage credentials used by the AI-Horde test stack so
# that no secret-looking values need to be committed to the repository.
#
# The rendered file is git-ignored and shared by both provisioning paths:
#   - docker-compose.yml mounts it into the garage service via env_file, so
#     Garage picks up GARAGE_RPC_SECRET / GARAGE_ADMIN_TOKEN / GARAGE_METRICS_TOKEN.
#   - bootstrap_garage.sh sources it for the S3 access key/secret it imports and
#     exports to the test process.
#
# Generation is idempotent: an existing, non-empty file is reused as-is. This is
# required because the compose stack keeps a persistent metadata volume whose
# node identity is derived from GARAGE_RPC_SECRET; regenerating it under a live
# volume would prevent Garage from starting. Use --force after tearing the stack
# down (docker compose down -v) to mint fresh values.

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
credentials_file="${AI_HORDE_TEST_GARAGE_CREDENTIALS_FILE:-$script_dir/.test-credentials.env}"
force=0

usage() {
  cat <<EOF
Usage: bash tests/garage/ensure_test_credentials.sh [--force]

Ensures the git-ignored Garage test credentials file exists, generating random
values on first use. Prints the absolute path of the credentials file.

Options:
  --force     Regenerate the credentials even if the file already exists.
  -h, --help  Show this help message.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      force=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

rand_hex() {
  local bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
  else
    head -c "$bytes" /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

if [[ "$force" == "1" ]]; then
  rm -f "$credentials_file"
fi

if [[ -s "$credentials_file" ]]; then
  printf '%s\n' "$credentials_file"
  exit 0
fi

umask 077
tmp_file="$(mktemp "${credentials_file}.XXXXXX")"
trap 'rm -f "$tmp_file"' EXIT

cat >"$tmp_file" <<EOF
# Generated by tests/garage/ensure_test_credentials.sh. Do not commit.
# Throwaway credentials for the local Garage test instance bound to localhost.
GARAGE_RPC_SECRET=$(rand_hex 32)
GARAGE_ADMIN_TOKEN=$(rand_hex 32)
GARAGE_METRICS_TOKEN=$(rand_hex 32)
AI_HORDE_TEST_GARAGE_ACCESS_KEY_ID=GK$(rand_hex 12)
AI_HORDE_TEST_GARAGE_SECRET_KEY=$(rand_hex 32)
EOF

mv "$tmp_file" "$credentials_file"
trap - EXIT
printf '%s\n' "$credentials_file"
