FROM postgres:15.3
RUN apt-get update && apt-get install -y postgresql-15-cron

RUN echo "shared_preload_libraries='pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample
RUN echo "cron.database_name='postgres'" >> /usr/share/postgresql/postgresql.conf.sample

COPY init-db /docker-entrypoint-initdb.d