import horde.apis.v2.base as base
import horde.apis.v2.stable as stable

base.api.add_resource(stable.ImageSyncGenerate, "/generate/sync")
base.api.add_resource(stable.ImageAsyncGenerate, "/generate/async")
base.api.add_resource(base.AsyncStatus, "/generate/status/<string:id>")
base.api.add_resource(base.AsyncCheck, "/generate/check/<string:id>")
base.api.add_resource(stable.Aesthetics, "/generate/rate/<string:id>")
base.api.add_resource(stable.ImageJobPop, "/generate/pop")
base.api.add_resource(base.JobSubmit, "/generate/submit")
base.api.add_resource(base.Users, "/users")
base.api.add_resource(base.UserSingle, "/users/<string:user_id>")
base.api.add_resource(base.FindUser, "/find_user")
base.api.add_resource(base.Workers, "/workers")
base.api.add_resource(base.WorkerSingle, "/workers/<string:worker_id>")
base.api.add_resource(base.TransferKudos, "/kudos/transfer")
base.api.add_resource(base.AwardKudos, "/kudos/award")
base.api.add_resource(base.HordeModes, "/status/modes")
base.api.add_resource(stable.HordeLoad, "/status/performance")
base.api.add_resource(base.Models, "/status/models")
base.api.add_resource(base.HordeNews, "/status/news")
base.api.add_resource(base.Heartbeat, "/status/heartbeat")
base.api.add_resource(base.Teams, "/teams")
base.api.add_resource(base.TeamSingle, "/teams/<string:team_id>")
base.api.add_resource(base.OperationsIP, "/operations/ipaddr")
base.api.add_resource(stable.Interrogate, "/interrogate/async")
base.api.add_resource(stable.InterrogationStatus, "/interrogate/status/<string:id>")
base.api.add_resource(stable.InterrogatePop, "/interrogate/pop")
#TODO APIv2 Merge with status as a POST this part of /interrogate/<string:id>
base.api.add_resource(stable.InterrogateSubmit, "/interrogate/submit")
base.api.add_resource(base.Filters, "/filters")
base.api.add_resource(base.FilterRegex, "/filters/regex")
base.api.add_resource(base.FilterSingle, "/filters/<string:filter_id>")
base.api.add_resource(stable.HordeStatsTotals, "/stats/img/totals")
base.api.add_resource(stable.HordeStatsModels, "/stats/img/models")
